# Generated by Django 4.0.4 on 2022-04-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emaillar',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nomre',
                'verbose_name_plural': 'Nomreler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Kod')),
                ('size', models.CharField(max_length=200, verbose_name='Ölcu')),
                ('address', models.CharField(max_length=5000, verbose_name='Ünvan')),
                ('retailer', models.CharField(max_length=500, verbose_name='Tədarükcü')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alış Qiyməti')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Qiymət')),
                ('support_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Qurlaşdirma Qiyməti')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
    ]
