# Generated by Django 4.0.4 on 2022-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_product_options_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emaillar',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nomre',
                'verbose_name_plural': 'Nomreler',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='', max_length=5000, verbose_name='Ünvan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Alış Qiyməti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.CharField(default='', max_length=500, verbose_name='Tədarükcü'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Qiymət'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=200, verbose_name='Ölcu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='support_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Qurlaşdirma Qiyməti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ad'),
        ),
    ]
